import type { MedicalMedicine } from "@/lib/types/medical";

export const medicalMedicines: MedicalMedicine[] = [
  {
    id: "mm-001",
    name: "Paracetamol 500mg Tablets",
    sku: "MED-PARA-500",
    barcode: "8901030000011",
    genericName: "Paracetamol",
    categoryId: "cat-analgesics",
    manufacturerId: "mfr-cipla",
    dosageForm: "Tablet",
    strength: "500mg",
    packSize: "10x10",
    unit: "Strip",
    purchasePrice: 1.5,
    sellingPrice: 2.2,
    mrp: 2.5,
    minimumStock: 100,
    prescriptionRequired: false,
    active: true,
  },
  {
    id: "mm-002",
    name: "Amoxicillin 500mg Capsules",
    sku: "MED-AMOX-500",
    barcode: "8901030000028",
    genericName: "Amoxicillin",
    categoryId: "cat-antibiotics",
    manufacturerId: "mfr-drreddys",
    dosageForm: "Capsule",
    strength: "500mg",
    packSize: "10x10",
    unit: "Strip",
    purchasePrice: 2.9,
    sellingPrice: 4.2,
    mrp: 4.8,
    minimumStock: 80,
    prescriptionRequired: true,
    active: true,
  },
  {
    id: "mm-003",
    name: "Cetirizine 10mg Tablets",
    sku: "MED-CETI-010",
    barcode: "8901030000035",
    genericName: "Cetirizine Hydrochloride",
    categoryId: "cat-antihistamines",
    manufacturerId: "mfr-sunpharma",
    dosageForm: "Tablet",
    strength: "10mg",
    packSize: "10x10",
    unit: "Strip",
    purchasePrice: 1.05,
    sellingPrice: 1.6,
    mrp: 1.8,
    minimumStock: 60,
    prescriptionRequired: false,
    active: true,
  },
  {
    id: "mm-004",
    name: "Vitamin C Effervescent Tablets",
    sku: "MED-VITC-1000",
    barcode: "8901030000042",
    genericName: "Ascorbic Acid",
    categoryId: "cat-vitamins",
    manufacturerId: "mfr-abbott",
    dosageForm: "Tablet",
    strength: "1000mg",
    packSize: "20s Tube",
    unit: "Tube",
    purchasePrice: 4.1,
    sellingPrice: 5.99,
    mrp: 6.5,
    minimumStock: 40,
    prescriptionRequired: false,
    active: true,
  },
  {
    id: "mm-005",
    name: "Dextromethorphan Cough Syrup 100ml",
    sku: "MED-COFS-100",
    barcode: "8901030000059",
    genericName: "Dextromethorphan",
    categoryId: "cat-cough-cold",
    manufacturerId: "mfr-gsk",
    dosageForm: "Syrup",
    strength: "15mg/5ml",
    packSize: "100ml Bottle",
    unit: "Bottle",
    purchasePrice: 3.2,
    sellingPrice: 4.75,
    mrp: 5.2,
    minimumStock: 30,
    prescriptionRequired: false,
    active: true,
  },
  {
    id: "mm-006",
    name: "Omeprazole 20mg Capsules",
    sku: "MED-OMEP-020",
    barcode: "8901030000066",
    genericName: "Omeprazole",
    categoryId: "cat-antacids",
    manufacturerId: "mfr-cipla",
    dosageForm: "Capsule",
    strength: "20mg",
    packSize: "10x10",
    unit: "Strip",
    purchasePrice: 2.3,
    sellingPrice: 3.5,
    mrp: 3.9,
    minimumStock: 50,
    prescriptionRequired: true,
    active: true,
  },
  {
    id: "mm-007",
    name: "Metformin 500mg Tablets",
    sku: "MED-METF-500",
    barcode: "8901030000073",
    genericName: "Metformin Hydrochloride",
    categoryId: "cat-cardiac-diabetes",
    manufacturerId: "mfr-sunpharma",
    dosageForm: "Tablet",
    strength: "500mg",
    packSize: "10x10",
    unit: "Strip",
    purchasePrice: 1.7,
    sellingPrice: 2.6,
    mrp: 2.9,
    minimumStock: 60,
    prescriptionRequired: true,
    active: true,
  },
  {
    id: "mm-008",
    name: "Atorvastatin 10mg Tablets",
    sku: "MED-ATOR-010",
    barcode: "8901030000080",
    genericName: "Atorvastatin Calcium",
    categoryId: "cat-cardiac-diabetes",
    manufacturerId: "mfr-drreddys",
    dosageForm: "Tablet",
    strength: "10mg",
    packSize: "10x10",
    unit: "Strip",
    purchasePrice: 3.4,
    sellingPrice: 5.1,
    mrp: 5.6,
    minimumStock: 50,
    prescriptionRequired: true,
    active: true,
  },
  {
    id: "mm-009",
    name: "Ibuprofen 400mg Tablets",
    sku: "MED-IBUP-400",
    barcode: "8901030000097",
    genericName: "Ibuprofen",
    categoryId: "cat-analgesics",
    manufacturerId: "mfr-abbott",
    dosageForm: "Tablet",
    strength: "400mg",
    packSize: "10x10",
    unit: "Strip",
    purchasePrice: 1.95,
    sellingPrice: 2.9,
    mrp: 3.2,
    minimumStock: 70,
    prescriptionRequired: false,
    active: true,
  },
  {
    id: "mm-010",
    name: "Azithromycin 250mg Tablets",
    sku: "MED-AZIT-250",
    barcode: "8901030000103",
    genericName: "Azithromycin",
    categoryId: "cat-antibiotics",
    manufacturerId: "mfr-gsk",
    dosageForm: "Tablet",
    strength: "250mg",
    packSize: "6s Strip",
    unit: "Strip",
    purchasePrice: 4.9,
    sellingPrice: 7.1,
    mrp: 7.8,
    minimumStock: 40,
    prescriptionRequired: true,
    active: true,
  },
  {
    id: "mm-011",
    name: "ORS Rehydration Sachets",
    sku: "MED-ORS-021",
    barcode: "8901030000110",
    genericName: "Oral Rehydration Salts",
    categoryId: "cat-antacids",
    manufacturerId: "mfr-cipla",
    dosageForm: "Sachet",
    strength: "21g",
    packSize: "1s Sachet",
    unit: "Sachet",
    purchasePrice: 0.45,
    sellingPrice: 0.75,
    mrp: 0.9,
    minimumStock: 100,
    prescriptionRequired: false,
    active: true,
  },
  {
    id: "mm-012",
    name: "Insulin Glargine Injection 10ml",
    sku: "MED-INSU-100",
    barcode: "8901030000127",
    genericName: "Insulin Glargine",
    categoryId: "cat-cardiac-diabetes",
    manufacturerId: "mfr-sunpharma",
    dosageForm: "Injection",
    strength: "100IU/ml",
    packSize: "10ml Vial",
    unit: "Vial",
    purchasePrice: 19.5,
    sellingPrice: 26.0,
    mrp: 28.5,
    minimumStock: 20,
    prescriptionRequired: true,
    active: true,
  },
  {
    id: "mm-013",
    name: "Multivitamin Tablets (Daily)",
    sku: "MED-MULT-030",
    barcode: "8901030000134",
    genericName: "Multivitamin & Minerals",
    categoryId: "cat-vitamins",
    manufacturerId: "mfr-abbott",
    dosageForm: "Tablet",
    strength: "Multi",
    packSize: "30s Bottle",
    unit: "Bottle",
    purchasePrice: 5.6,
    sellingPrice: 7.99,
    mrp: 8.9,
    minimumStock: 40,
    prescriptionRequired: false,
    active: true,
  },
  {
    id: "mm-014",
    name: "Aspirin 75mg Tablets",
    sku: "MED-ASPI-075",
    barcode: "8901030000141",
    genericName: "Acetylsalicylic Acid",
    categoryId: "cat-cardiac-diabetes",
    manufacturerId: "mfr-drreddys",
    dosageForm: "Tablet",
    strength: "75mg",
    packSize: "14x10",
    unit: "Strip",
    purchasePrice: 0.85,
    sellingPrice: 1.3,
    mrp: 1.5,
    minimumStock: 50,
    prescriptionRequired: false,
    active: true,
  },
];
