import type { MedicalMedicine } from "@/lib/types/medical";

export const medicalMedicines: MedicalMedicine[] = [
  {
    id: "mm-001",
    name: "Paracetamol 500mg Tablets",
    sku: "MED-PARA-500",
    genericName: "Paracetamol",
    categoryId: "cat-analgesics",
    manufacturerId: "mfr-cipla",
    batchNumber: "BN-24A017",
    manufacturingDate: "2025-03-10",
    expiryDate: "2027-03-09",
    mrp: 2.5,
    price: 2.2,
    costPrice: 1.5,
    stockQty: 480,
    reorderLevel: 100,
    prescriptionRequired: false,
  },
  {
    id: "mm-002",
    name: "Amoxicillin 500mg Capsules",
    sku: "MED-AMOX-500",
    genericName: "Amoxicillin",
    categoryId: "cat-antibiotics",
    manufacturerId: "mfr-drreddys",
    batchNumber: "BN-24B102",
    manufacturingDate: "2025-01-15",
    expiryDate: "2026-09-20",
    mrp: 4.8,
    price: 4.2,
    costPrice: 2.9,
    stockQty: 60,
    reorderLevel: 80,
    prescriptionRequired: true,
  },
  {
    id: "mm-003",
    name: "Cetirizine 10mg Tablets",
    sku: "MED-CETI-010",
    genericName: "Cetirizine Hydrochloride",
    categoryId: "cat-antihistamines",
    manufacturerId: "mfr-sunpharma",
    batchNumber: "BN-24C045",
    manufacturingDate: "2025-02-01",
    expiryDate: "2027-01-31",
    mrp: 1.8,
    price: 1.6,
    costPrice: 1.05,
    stockQty: 320,
    reorderLevel: 60,
    prescriptionRequired: false,
  },
  {
    id: "mm-004",
    name: "Vitamin C Effervescent Tablets",
    sku: "MED-VITC-1000",
    genericName: "Ascorbic Acid",
    categoryId: "cat-vitamins",
    manufacturerId: "mfr-abbott",
    batchNumber: "BN-24D089",
    manufacturingDate: "2025-04-05",
    expiryDate: "2027-04-04",
    mrp: 6.5,
    price: 5.99,
    costPrice: 4.1,
    stockQty: 150,
    reorderLevel: 40,
    prescriptionRequired: false,
  },
  {
    id: "mm-005",
    name: "Dextromethorphan Cough Syrup 100ml",
    sku: "MED-COFS-100",
    genericName: "Dextromethorphan",
    categoryId: "cat-cough-cold",
    manufacturerId: "mfr-gsk",
    batchNumber: "BN-24E211",
    manufacturingDate: "2025-05-12",
    expiryDate: "2026-09-10",
    mrp: 5.2,
    price: 4.75,
    costPrice: 3.2,
    stockQty: 25,
    reorderLevel: 30,
    prescriptionRequired: false,
  },
  {
    id: "mm-006",
    name: "Omeprazole 20mg Capsules",
    sku: "MED-OMEP-020",
    genericName: "Omeprazole",
    categoryId: "cat-antacids",
    manufacturerId: "mfr-cipla",
    batchNumber: "BN-24F033",
    manufacturingDate: "2025-01-20",
    expiryDate: "2027-06-19",
    mrp: 3.9,
    price: 3.5,
    costPrice: 2.3,
    stockQty: 210,
    reorderLevel: 50,
    prescriptionRequired: true,
  },
  {
    id: "mm-007",
    name: "Metformin 500mg Tablets",
    sku: "MED-METF-500",
    genericName: "Metformin Hydrochloride",
    categoryId: "cat-cardiac-diabetes",
    manufacturerId: "mfr-sunpharma",
    batchNumber: "BN-24G077",
    manufacturingDate: "2025-03-22",
    expiryDate: "2027-03-21",
    mrp: 2.9,
    price: 2.6,
    costPrice: 1.7,
    stockQty: 275,
    reorderLevel: 60,
    prescriptionRequired: true,
  },
  {
    id: "mm-008",
    name: "Atorvastatin 10mg Tablets",
    sku: "MED-ATOR-010",
    genericName: "Atorvastatin Calcium",
    categoryId: "cat-cardiac-diabetes",
    manufacturerId: "mfr-drreddys",
    batchNumber: "BN-24H154",
    manufacturingDate: "2025-02-14",
    expiryDate: "2026-09-25",
    mrp: 5.6,
    price: 5.1,
    costPrice: 3.4,
    stockQty: 40,
    reorderLevel: 50,
    prescriptionRequired: true,
  },
  {
    id: "mm-009",
    name: "Ibuprofen 400mg Tablets",
    sku: "MED-IBUP-400",
    genericName: "Ibuprofen",
    categoryId: "cat-analgesics",
    manufacturerId: "mfr-abbott",
    batchNumber: "BN-24I098",
    manufacturingDate: "2025-04-18",
    expiryDate: "2027-04-17",
    mrp: 3.2,
    price: 2.9,
    costPrice: 1.95,
    stockQty: 300,
    reorderLevel: 70,
    prescriptionRequired: false,
  },
  {
    id: "mm-010",
    name: "Azithromycin 250mg Tablets",
    sku: "MED-AZIT-250",
    genericName: "Azithromycin",
    categoryId: "cat-antibiotics",
    manufacturerId: "mfr-gsk",
    batchNumber: "BN-24J066",
    manufacturingDate: "2025-05-02",
    expiryDate: "2027-05-01",
    mrp: 7.8,
    price: 7.1,
    costPrice: 4.9,
    stockQty: 95,
    reorderLevel: 40,
    prescriptionRequired: true,
  },
  {
    id: "mm-011",
    name: "ORS Rehydration Sachets",
    sku: "MED-ORS-021",
    genericName: "Oral Rehydration Salts",
    categoryId: "cat-antacids",
    manufacturerId: "mfr-cipla",
    batchNumber: "BN-24K012",
    manufacturingDate: "2025-06-01",
    expiryDate: "2027-05-31",
    mrp: 0.9,
    price: 0.75,
    costPrice: 0.45,
    stockQty: 500,
    reorderLevel: 100,
    prescriptionRequired: false,
  },
  {
    id: "mm-012",
    name: "Insulin Glargine Injection 10ml",
    sku: "MED-INSU-100",
    genericName: "Insulin Glargine",
    categoryId: "cat-cardiac-diabetes",
    manufacturerId: "mfr-sunpharma",
    batchNumber: "BN-24L200",
    manufacturingDate: "2025-07-08",
    expiryDate: "2026-09-16",
    mrp: 28.5,
    price: 26.0,
    costPrice: 19.5,
    stockQty: 18,
    reorderLevel: 20,
    prescriptionRequired: true,
  },
  {
    id: "mm-013",
    name: "Multivitamin Tablets (Daily)",
    sku: "MED-MULT-030",
    genericName: "Multivitamin & Minerals",
    categoryId: "cat-vitamins",
    manufacturerId: "mfr-abbott",
    batchNumber: "BN-24M156",
    manufacturingDate: "2025-03-30",
    expiryDate: "2027-03-29",
    mrp: 8.9,
    price: 7.99,
    costPrice: 5.6,
    stockQty: 180,
    reorderLevel: 40,
    prescriptionRequired: false,
  },
  {
    id: "mm-014",
    name: "Aspirin 75mg Tablets",
    sku: "MED-ASPI-075",
    genericName: "Acetylsalicylic Acid",
    categoryId: "cat-cardiac-diabetes",
    manufacturerId: "mfr-drreddys",
    batchNumber: "BN-24N044",
    manufacturingDate: "2025-02-25",
    expiryDate: "2027-02-24",
    mrp: 1.5,
    price: 1.3,
    costPrice: 0.85,
    stockQty: 260,
    reorderLevel: 50,
    prescriptionRequired: false,
  },
];
