import type { MedicalSale } from "@/lib/types/medical";

export const medicalSales: MedicalSale[] = [
  {
    id: "msa-001",
    customerId: "mc-001",
    customerName: "Priya Sharma",
    date: "2026-09-10",
    status: "completed",
    items: [
      {
        productId: "mm-001",
        productName: "Paracetamol 500mg Tablets",
        quantity: 2,
        unitPrice: 2.2,
        batchAllocations: [{ batchId: "mbatch-001", batchNumber: "BN-24A017", quantity: 2 }],
      },
      {
        productId: "mm-004",
        productName: "Vitamin C Effervescent Tablets",
        quantity: 1,
        unitPrice: 5.99,
        batchAllocations: [{ batchId: "mbatch-005", batchNumber: "BN-24D089", quantity: 1 }],
      },
    ],
    total: 10.39,
  },
  {
    id: "msa-002",
    customerId: "mc-002",
    customerName: "Rohan Mehta",
    date: "2026-09-10",
    status: "completed",
    prescriptionId: "mrx-001",
    items: [
      {
        productId: "mm-002",
        productName: "Amoxicillin 500mg Capsules",
        quantity: 1,
        unitPrice: 4.2,
        batchAllocations: [{ batchId: "mbatch-003", batchNumber: "BN-24B102", quantity: 1 }],
      },
      {
        productId: "mm-006",
        productName: "Omeprazole 20mg Capsules",
        quantity: 1,
        unitPrice: 3.5,
        batchAllocations: [{ batchId: "mbatch-008", batchNumber: "BN-24F034", quantity: 1 }],
      },
    ],
    total: 7.7,
  },
  {
    id: "msa-003",
    customerId: "mc-005",
    customerName: "Neha Kapoor",
    date: "2026-09-09",
    status: "completed",
    items: [
      {
        productId: "mm-007",
        productName: "Metformin 500mg Tablets",
        quantity: 2,
        unitPrice: 2.6,
        batchAllocations: [{ batchId: "mbatch-009", batchNumber: "BN-24G077", quantity: 2 }],
      },
      {
        productId: "mm-008",
        productName: "Atorvastatin 10mg Tablets",
        quantity: 1,
        unitPrice: 5.1,
        batchAllocations: [{ batchId: "mbatch-010", batchNumber: "BN-24H154", quantity: 1 }],
      },
    ],
    total: 10.3,
  },
  {
    id: "msa-004",
    customerId: "mc-003",
    customerName: "Ayesha Khan",
    date: "2026-09-08",
    status: "pending",
    items: [{ productId: "mm-003", productName: "Cetirizine 10mg Tablets", quantity: 1, unitPrice: 1.6 }],
    total: 1.6,
  },
  {
    id: "msa-005",
    customerId: "mc-004",
    customerName: "Arjun Nair",
    date: "2026-09-07",
    status: "completed",
    items: [
      {
        productId: "mm-011",
        productName: "ORS Rehydration Sachets",
        quantity: 5,
        unitPrice: 0.75,
        batchAllocations: [{ batchId: "mbatch-013", batchNumber: "BN-24K012", quantity: 5 }],
      },
      {
        productId: "mm-005",
        productName: "Dextromethorphan Cough Syrup 100ml",
        quantity: 1,
        unitPrice: 4.75,
        batchAllocations: [{ batchId: "mbatch-006", batchNumber: "BN-24E211", quantity: 1 }],
      },
    ],
    total: 8.5,
  },
  {
    id: "msa-006",
    customerId: "mc-006",
    customerName: "Karan Malhotra",
    date: "2026-09-05",
    status: "cancelled",
    items: [{ productId: "mm-013", productName: "Multivitamin Tablets (Daily)", quantity: 1, unitPrice: 7.99 }],
    total: 7.99,
  },
];
