import type { ElectronicsProduct } from "@/lib/types/electronics";

export const electronicsProducts: ElectronicsProduct[] = [
  // Smartphones — IMEI tracked, no separate serial
  {
    id: "ep-001",
    name: "iPhone 15 128GB",
    sku: "EL-IPH15-128",
    categoryId: "ecat-smartphones",
    brandId: "ebrand-apple",
    modelId: "emodel-iphone15",
    price: 799,
    costPrice: 650,
    stockQty: 34,
    reorderLevel: 10,
    warrantyMonths: 12,
    hasImei: true,
    hasSerial: false,
    specifications: { Storage: "128GB", RAM: "6GB", Display: "6.1-inch Super Retina XDR", Color: "Blue" },
  },
  {
    id: "ep-002",
    name: "iPhone 15 256GB",
    sku: "EL-IPH15-256",
    categoryId: "ecat-smartphones",
    brandId: "ebrand-apple",
    modelId: "emodel-iphone15",
    price: 899,
    costPrice: 730,
    stockQty: 18,
    reorderLevel: 8,
    warrantyMonths: 12,
    hasImei: true,
    hasSerial: false,
    specifications: { Storage: "256GB", RAM: "6GB", Display: "6.1-inch Super Retina XDR", Color: "Black" },
  },
  {
    id: "ep-003",
    name: "iPhone 15 Pro 256GB",
    sku: "EL-IPH15P-256",
    categoryId: "ecat-smartphones",
    brandId: "ebrand-apple",
    modelId: "emodel-iphone15pro",
    price: 999,
    costPrice: 830,
    stockQty: 12,
    reorderLevel: 6,
    warrantyMonths: 12,
    hasImei: true,
    hasSerial: false,
    specifications: {
      Storage: "256GB",
      RAM: "8GB",
      Display: "6.1-inch Super Retina XDR ProMotion",
      Color: "Natural Titanium",
    },
  },
  {
    id: "ep-004",
    name: "Samsung Galaxy S24 128GB",
    sku: "EL-GS24-128",
    categoryId: "ecat-smartphones",
    brandId: "ebrand-samsung",
    modelId: "emodel-galaxys24",
    price: 749,
    costPrice: 600,
    stockQty: 27,
    reorderLevel: 10,
    warrantyMonths: 12,
    hasImei: true,
    hasSerial: false,
    specifications: { Storage: "128GB", RAM: "8GB", Display: "6.2-inch Dynamic AMOLED 2X", Color: "Onyx Black" },
  },
  {
    id: "ep-005",
    name: "Samsung Galaxy S24 Ultra 512GB",
    sku: "EL-GS24U-512",
    categoryId: "ecat-smartphones",
    brandId: "ebrand-samsung",
    modelId: "emodel-galaxys24ultra",
    price: 1419,
    costPrice: 1180,
    stockQty: 9,
    reorderLevel: 5,
    warrantyMonths: 12,
    hasImei: true,
    hasSerial: false,
    specifications: {
      Storage: "512GB",
      RAM: "12GB",
      Display: "6.8-inch Dynamic AMOLED 2X",
      Color: "Titanium Gray",
    },
  },
  {
    id: "ep-006",
    name: "OnePlus 12 256GB",
    sku: "EL-OP12-256",
    categoryId: "ecat-smartphones",
    brandId: "ebrand-oneplus",
    modelId: "emodel-oneplus12",
    price: 799,
    costPrice: 640,
    stockQty: 15,
    reorderLevel: 8,
    warrantyMonths: 12,
    hasImei: true,
    hasSerial: false,
    specifications: { Storage: "256GB", RAM: "12GB", Display: "6.82-inch AMOLED", Color: "Flowy Emerald" },
  },
  {
    id: "ep-007",
    name: "Google Pixel 8 128GB",
    sku: "EL-PIX8-128",
    categoryId: "ecat-smartphones",
    brandId: "ebrand-google",
    modelId: "emodel-pixel8",
    price: 699,
    costPrice: 560,
    stockQty: 4,
    reorderLevel: 8,
    warrantyMonths: 12,
    hasImei: true,
    hasSerial: false,
    specifications: { Storage: "128GB", RAM: "8GB", Display: "6.2-inch OLED", Color: "Obsidian" },
  },

  // Laptops — serial tracked, no IMEI
  {
    id: "ep-008",
    name: "Dell Inspiron 15 3000 (i5/8GB/512GB)",
    sku: "EL-DELLINS15-512",
    categoryId: "ecat-laptops",
    brandId: "ebrand-dell",
    modelId: "emodel-inspiron15",
    price: 549,
    costPrice: 430,
    stockQty: 16,
    reorderLevel: 6,
    warrantyMonths: 24,
    hasImei: false,
    hasSerial: true,
    specifications: { CPU: "Intel Core i5-1235U", RAM: "8GB", Storage: "512GB SSD", Display: "15.6-inch FHD" },
  },
  {
    id: "ep-009",
    name: "Dell XPS 13 (i7/16GB/512GB)",
    sku: "EL-DELLXPS13-512",
    categoryId: "ecat-laptops",
    brandId: "ebrand-dell",
    modelId: "emodel-xps13",
    price: 1299,
    costPrice: 1050,
    stockQty: 7,
    reorderLevel: 5,
    warrantyMonths: 24,
    hasImei: false,
    hasSerial: true,
    specifications: { CPU: "Intel Core i7-1355U", RAM: "16GB", Storage: "512GB SSD", Display: "13.4-inch FHD+" },
  },
  {
    id: "ep-010",
    name: "HP Pavilion 15 (i5/8GB/256GB)",
    sku: "EL-HPPAV15-256",
    categoryId: "ecat-laptops",
    brandId: "ebrand-hp",
    modelId: "emodel-pavilion15",
    price: 599,
    costPrice: 470,
    stockQty: 3,
    reorderLevel: 6,
    warrantyMonths: 12,
    hasImei: false,
    hasSerial: true,
    specifications: { CPU: "Intel Core i5-1335U", RAM: "8GB", Storage: "256GB SSD", Display: "15.6-inch FHD" },
  },
  {
    id: "ep-011",
    name: "Lenovo ThinkPad E14 (i5/16GB/512GB)",
    sku: "EL-LENE14-512",
    categoryId: "ecat-laptops",
    brandId: "ebrand-lenovo",
    modelId: "emodel-thinkpade14",
    price: 899,
    costPrice: 720,
    stockQty: 11,
    reorderLevel: 5,
    warrantyMonths: 36,
    hasImei: false,
    hasSerial: true,
    specifications: { CPU: "Intel Core i5-1335U", RAM: "16GB", Storage: "512GB SSD", Display: "14-inch FHD" },
  },
  {
    id: "ep-012",
    name: "ASUS Vivobook 15 (i5/8GB/512GB)",
    sku: "EL-ASUSVB15-512",
    categoryId: "ecat-laptops",
    brandId: "ebrand-asus",
    modelId: "emodel-vivobook15",
    price: 629,
    costPrice: 495,
    stockQty: 14,
    reorderLevel: 6,
    warrantyMonths: 24,
    hasImei: false,
    hasSerial: true,
    specifications: { CPU: "Intel Core i5-1235U", RAM: "8GB", Storage: "512GB SSD", Display: "15.6-inch FHD" },
  },

  // Audio — no unit-level tracking
  {
    id: "ep-013",
    name: "Sony WH-1000XM5 Headphones",
    sku: "EL-SONYXM5",
    categoryId: "ecat-audio",
    brandId: "ebrand-sony",
    modelId: "emodel-wh1000xm5",
    price: 399,
    costPrice: 290,
    stockQty: 22,
    reorderLevel: 8,
    warrantyMonths: 12,
    hasImei: false,
    hasSerial: false,
    specifications: { Type: "Over-ear, Noise Cancelling", Battery: "30 hours", Connectivity: "Bluetooth 5.2" },
  },
  {
    id: "ep-014",
    name: "JBL Flip 6 Portable Speaker",
    sku: "EL-JBLFLIP6",
    categoryId: "ecat-audio",
    brandId: "ebrand-jbl",
    modelId: "emodel-jblflip6",
    price: 129,
    costPrice: 85,
    stockQty: 30,
    reorderLevel: 10,
    warrantyMonths: 12,
    hasImei: false,
    hasSerial: false,
    specifications: { Type: "Portable Bluetooth Speaker", Battery: "12 hours", Waterproof: "IP67" },
  },
  {
    id: "ep-015",
    name: "JBL Charge 5 Portable Speaker",
    sku: "EL-JBLCHARGE5",
    categoryId: "ecat-audio",
    brandId: "ebrand-jbl",
    modelId: "emodel-jblcharge5",
    price: 179,
    costPrice: 125,
    stockQty: 5,
    reorderLevel: 8,
    warrantyMonths: 12,
    hasImei: false,
    hasSerial: false,
    specifications: { Type: "Portable Bluetooth Speaker", Battery: "20 hours", Waterproof: "IP67" },
  },

  // Accessories
  {
    id: "ep-016",
    name: "Logitech MX Master 3S Mouse",
    sku: "EL-LOGIMXM3S",
    categoryId: "ecat-accessories",
    brandId: "ebrand-logitech",
    modelId: "emodel-mxmaster3s",
    price: 99,
    costPrice: 65,
    stockQty: 40,
    reorderLevel: 12,
    warrantyMonths: 12,
    hasImei: false,
    hasSerial: false,
    specifications: { Type: "Wireless Mouse", Connectivity: "Bluetooth / USB Receiver", DPI: "8000" },
  },
  {
    id: "ep-017",
    name: "Logitech MX Keys Keyboard",
    sku: "EL-LOGIMXK",
    categoryId: "ecat-accessories",
    brandId: "ebrand-logitech",
    modelId: "emodel-mxkeys",
    price: 109,
    costPrice: 72,
    stockQty: 25,
    reorderLevel: 10,
    warrantyMonths: 12,
    hasImei: false,
    hasSerial: false,
    specifications: { Type: "Wireless Keyboard", Backlit: "Yes", Connectivity: "Bluetooth / USB Receiver" },
  },
  {
    id: "ep-018",
    name: "Logitech G502 Hero Gaming Mouse",
    sku: "EL-LOGIG502",
    categoryId: "ecat-accessories",
    brandId: "ebrand-logitech",
    modelId: "emodel-g502",
    price: 59,
    costPrice: 38,
    stockQty: 33,
    reorderLevel: 12,
    warrantyMonths: 12,
    hasImei: false,
    hasSerial: false,
    specifications: { Type: "Wired Gaming Mouse", DPI: "25600", Buttons: "11 programmable" },
  },
  {
    id: "ep-019",
    name: "Anker PowerCore 20000 Power Bank",
    sku: "EL-ANKPC20K",
    categoryId: "ecat-accessories",
    brandId: "ebrand-anker",
    modelId: "emodel-powercore20k",
    price: 55,
    costPrice: 34,
    stockQty: 45,
    reorderLevel: 15,
    warrantyMonths: 18,
    hasImei: false,
    hasSerial: false,
    specifications: { Capacity: "20000mAh", Output: "18W PD", Ports: "2x USB-A, 1x USB-C" },
  },
  {
    id: "ep-020",
    name: "Anker PowerPort III 65W Charger",
    sku: "EL-ANKPP65W",
    categoryId: "ecat-accessories",
    brandId: "ebrand-anker",
    modelId: "emodel-powerport65w",
    price: 39,
    costPrice: 24,
    stockQty: 6,
    reorderLevel: 12,
    warrantyMonths: 18,
    hasImei: false,
    hasSerial: false,
    specifications: { Output: "65W GaN", Ports: "2x USB-C, 1x USB-A" },
  },

  // Monitors — serial tracked
  {
    id: "ep-021",
    name: "Dell UltraSharp U2723QE 27\" Monitor",
    sku: "EL-DELLUS27",
    categoryId: "ecat-monitors",
    brandId: "ebrand-dell",
    modelId: "emodel-ultrasharp27",
    price: 579,
    costPrice: 460,
    stockQty: 10,
    reorderLevel: 5,
    warrantyMonths: 36,
    hasImei: false,
    hasSerial: true,
    specifications: { Resolution: "3840x2160", PanelType: "IPS Black", RefreshRate: "60Hz" },
  },
  {
    id: "ep-022",
    name: "ASUS ProArt PA278QV 27\" Monitor",
    sku: "EL-ASUSPA27",
    categoryId: "ecat-monitors",
    brandId: "ebrand-asus",
    modelId: "emodel-proart27",
    price: 329,
    costPrice: 255,
    stockQty: 8,
    reorderLevel: 5,
    warrantyMonths: 36,
    hasImei: false,
    hasSerial: true,
    specifications: { Resolution: "2560x1440", PanelType: "IPS", RefreshRate: "75Hz" },
  },

  // Storage — serial tracked
  {
    id: "ep-023",
    name: "Samsung 990 Pro SSD 1TB",
    sku: "EL-SAM990PRO-1TB",
    categoryId: "ecat-storage",
    brandId: "ebrand-samsung",
    modelId: "emodel-990pro",
    price: 129,
    costPrice: 92,
    stockQty: 28,
    reorderLevel: 10,
    warrantyMonths: 60,
    hasImei: false,
    hasSerial: true,
    specifications: { Capacity: "1TB", Interface: "PCIe 4.0 NVMe", ReadSpeed: "7450 MB/s" },
  },
  {
    id: "ep-024",
    name: "WD Black SN850X SSD 2TB",
    sku: "EL-WDSN850X-2TB",
    categoryId: "ecat-storage",
    brandId: "ebrand-wd",
    modelId: "emodel-sn850x",
    price: 179,
    costPrice: 135,
    stockQty: 2,
    reorderLevel: 8,
    warrantyMonths: 60,
    hasImei: false,
    hasSerial: true,
    specifications: { Capacity: "2TB", Interface: "PCIe 4.0 NVMe", ReadSpeed: "7300 MB/s" },
  },

  // Wearables — serial tracked
  {
    id: "ep-025",
    name: "Samsung Galaxy Watch 6 44mm",
    sku: "EL-GWATCH6-44",
    categoryId: "ecat-wearables",
    brandId: "ebrand-samsung",
    modelId: "emodel-watch6",
    price: 329,
    costPrice: 250,
    stockQty: 13,
    reorderLevel: 6,
    warrantyMonths: 12,
    hasImei: false,
    hasSerial: true,
    specifications: { Display: "1.5-inch AMOLED", Battery: "40 hours", CaseSize: "44mm" },
  },
  {
    id: "ep-026",
    name: "Apple Watch Series 9 45mm",
    sku: "EL-AWATCH9-45",
    categoryId: "ecat-wearables",
    brandId: "ebrand-apple",
    modelId: "emodel-applewatch9",
    price: 429,
    costPrice: 340,
    stockQty: 17,
    reorderLevel: 6,
    warrantyMonths: 12,
    hasImei: false,
    hasSerial: true,
    specifications: { Display: "1.9-inch Retina LTPO OLED", Battery: "18 hours", CaseSize: "45mm" },
  },
  {
    id: "ep-027",
    name: "Dell XPS 13 Plus (i7/32GB/1TB)",
    sku: "EL-DELLXPS13P-1TB",
    categoryId: "ecat-laptops",
    brandId: "ebrand-dell",
    modelId: "emodel-xps13",
    price: 1699,
    costPrice: 1400,
    stockQty: 4,
    reorderLevel: 4,
    warrantyMonths: 24,
    hasImei: false,
    hasSerial: true,
    specifications: { CPU: "Intel Core i7-1370P", RAM: "32GB", Storage: "1TB SSD", Display: "13.4-inch OLED" },
  },
  {
    id: "ep-028",
    name: "Samsung Galaxy S24 Ultra 256GB",
    sku: "EL-GS24U-256",
    categoryId: "ecat-smartphones",
    brandId: "ebrand-samsung",
    modelId: "emodel-galaxys24ultra",
    price: 1299,
    costPrice: 1070,
    stockQty: 0,
    reorderLevel: 5,
    warrantyMonths: 12,
    hasImei: true,
    hasSerial: false,
    specifications: {
      Storage: "256GB",
      RAM: "12GB",
      Display: "6.8-inch Dynamic AMOLED 2X",
      Color: "Titanium Violet",
    },
  },
];
