import type { ElectronicsReturn } from "@/lib/types/electronics";

export const electronicsReturns: ElectronicsReturn[] = [
  {
    id: "eret-001",
    productId: "ep-013",
    productName: "Sony WH-1000XM5 Headphones",
    serialNumber: "SVC-XM5-91004",
    customerId: "ecu-003",
    customerName: "Jonas Weber",
    saleId: "esa-003",
    date: "2026-09-10",
    reason: "defective",
    status: "approved",
  },
  {
    id: "eret-002",
    productId: "ep-010",
    productName: "HP Pavilion 15 (i5/8GB/256GB)",
    serialNumber: "SVC-PAV15-19102",
    customerId: "ecu-004",
    customerName: "Aisha Rahman",
    date: "2026-09-14",
    reason: "damaged",
    status: "pending",
  },
  {
    id: "eret-003",
    productId: "ep-006",
    productName: "OnePlus 12 256GB",
    serialNumber: "",
    customerId: "ecu-003",
    customerName: "Jonas Weber",
    saleId: "esa-012",
    date: "2026-09-13",
    reason: "changed_mind",
    status: "rejected",
  },
  {
    id: "eret-004",
    productId: "ep-016",
    productName: "Logitech MX Master 3S Mouse",
    serialNumber: "",
    customerId: "ecu-002",
    customerName: "Priya Nair",
    date: "2026-09-12",
    reason: "wrong_item",
    status: "approved",
  },
  {
    id: "eret-005",
    productId: "ep-005",
    productName: "Samsung Galaxy S24 Ultra 512GB",
    serialNumber: "SN-GS24U-55302",
    customerId: "ecu-006",
    customerName: "Lena Kowalski",
    saleId: "esa-006",
    date: "2026-09-11",
    reason: "warranty_claim",
    status: "pending",
  },
];
